databases:
  - name: language_learning_db
    databaseName: language_learning_db
    user: language_learning_user

services:
  - type: web
    name: language-learning-app
    env: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "./bin/render-start.sh"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: language_learning_db
          database: language_learning_db
          user: language_learning_user
      - key: SECRET_KEY_BASE
        generateValue: true
